--------------------------------------------------------
--  File created - Friday-May-05-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HRFORMS2_REQUESTS_JOURNAL_ARCHIVE
--------------------------------------------------------

  CREATE TABLE "BUHR"."HRFORMS2_REQUESTS_JOURNAL_ARCHIVE" 
   (	"REQUEST_ID" NUMBER(10,0), 
	"JOURNAL_DATE" TIMESTAMP (6), 
	"SUNY_ID" NUMBER(10,0), 
	"STATUS" VARCHAR2(1) COLLATE "USING_NLS_COMP", 
	"HIERARCHY_ID" NUMBER(10,0), 
	"WORKFLOW_ID" NUMBER(10,0), 
	"SEQUENCE" NUMBER(4,0), 
	"GROUP_FROM" NUMBER(10,0), 
	"GROUP_TO" NUMBER(10,0), 
	"COMMENTS" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" 
  PARTITION BY RANGE ("JOURNAL_DATE") INTERVAL (NUMTOYMINTERVAL(1,'YEAR')) 
 (PARTITION "REQUESTS_BEFORE_2022"  VALUES LESS THAN (TO_DATE(' 2022-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;

--------------------------------------------------------
--  Constraints for Table HRFORMS2_REQUESTS_JOURNAL_ARCHIVE
--------------------------------------------------------

  ALTER TABLE "BUHR"."HRFORMS2_REQUESTS_JOURNAL_ARCHIVE" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "BUHR"."HRFORMS2_REQUESTS_JOURNAL_ARCHIVE" MODIFY ("JOURNAL_DATE" NOT NULL ENABLE);
  ALTER TABLE "BUHR"."HRFORMS2_REQUESTS_JOURNAL_ARCHIVE" MODIFY ("SUNY_ID" NOT NULL ENABLE);
  ALTER TABLE "BUHR"."HRFORMS2_REQUESTS_JOURNAL_ARCHIVE" MODIFY ("STATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table HRFORMS2_REQUESTS_JOURNAL_ARCHIVE
--------------------------------------------------------

  ALTER TABLE "BUHR"."HRFORMS2_REQUESTS_JOURNAL_ARCHIVE" ADD CONSTRAINT "HRFORMS2_REQUESTS_JOURNAL_ARCHIVE_FK1" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "BUHR"."HRFORMS2_REQUESTS_ARCHIVE" ("REQUEST_ID") ON DELETE CASCADE ENABLE;
