--------------------------------------------------------
--  File created - Wednesday-April-06-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HRFORMS2_REQUESTS_ARCHIVE
--------------------------------------------------------

  CREATE TABLE "BUHR"."HRFORMS2_REQUESTS_ARCHIVE" 
   (	"REQUEST_ID" NUMBER(10,0), 
	"CREATED_BY" CLOB COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" DATE, 
	"REQUEST_DATA" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" 
  PARTITION BY RANGE ("CREATED_DATE") INTERVAL (NUMTOYMINTERVAL(1,'YEAR')) 
 (PARTITION "REQUESTS_BEFORE_2022"  VALUES LESS THAN (TO_DATE(' 2022-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
--------------------------------------------------------
--  DDL for Index HRFORMS2_REQUESTS_ARCHIVE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUHR"."HRFORMS2_REQUESTS_ARCHIVE_PK" ON "BUHR"."HRFORMS2_REQUESTS_ARCHIVE" ("REQUEST_ID") 
  ;
--------------------------------------------------------
--  Constraints for Table HRFORMS2_REQUESTS_ARCHIVE
--------------------------------------------------------

  ALTER TABLE "BUHR"."HRFORMS2_REQUESTS_ARCHIVE" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "BUHR"."HRFORMS2_REQUESTS_ARCHIVE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "BUHR"."HRFORMS2_REQUESTS_ARCHIVE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "BUHR"."HRFORMS2_REQUESTS_ARCHIVE" ADD CONSTRAINT "HRFORMS2_REQUESTS_ARCHIVE_CHK1" CHECK (created_by is JSON) ENABLE;
  ALTER TABLE "BUHR"."HRFORMS2_REQUESTS_ARCHIVE" ADD CONSTRAINT "HRFORMS2_REQUESTS_ARCHIVE_CHK2" CHECK (request_data is JSON) ENABLE;
  ALTER TABLE "BUHR"."HRFORMS2_REQUESTS_ARCHIVE" ADD CONSTRAINT "HRFORMS2_REQUESTS_ARCHIVE_PK" PRIMARY KEY ("REQUEST_ID")
  USING INDEX  ENABLE;
